MusicServiceInfrastructure/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Humanizer.Localisation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicServiceDomain.Model;

namespace MusicServiceInfrastructure.Controllers
{
    public class AlbumsController : Controller
    {
        private readonly DbmusicServiceContext _context;

        public AlbumsController(DbmusicServiceContext context)
        {
            _context = context;
        }

        // GET: Albums
        public async Task<IActionResult> Index()
        {
            return View(await _context.Albums.ToListAsync());
        }

        // GET: Albums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albums
                .FirstOrDefaultAsync(m => m.Id == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // GET: Albums/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Albums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,ReleaseYear,Id")] Album album)
        {
            if (ModelState.IsValid)
            {
                _context.Add(album);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(album);
        }

        // GET: Albums/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albums.FindAsync(id);
            if (album == null)
            {
                return NotFound();
            }
            return View(album);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,ReleaseYear,Id")] Album album)
        {
            if (id != album.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(album);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlbumExists(album.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(album);
        }

        // GET: Albums/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albums
                .FirstOrDefaultAsync(m => m.Id == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var album = await _context.Albums.FindAsync(id);
            if (album != null)
            {
                _context.Albums.Remove(album);
            }

            var songsInAlbum = await _context.Songs.Where(s => s.AlbumId == id).ToListAsync();
            if (songsInAlbum.Any())
            {
                ModelState.AddModelError("", "Не можна видалити альбом, якщо в ньому є пісні");
                return View("Delete", album);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlbumExists(int id)
        {
            return _context.Albums.Any(e => e.Id == id);
        }
    }
}

MusicServiceInfrastructure/Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using MusicServiceInfrastructure.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MusicServiceDomain.Model;

namespace MusicServiceInfrastructure.Controllers
{
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());
        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }

    }

}

MusicServiceInfrastructure/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Bibliography;
using DocumentFormat.OpenXml.Office2010.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using Humanizer.Localisation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicServiceDomain.Model;
using MusicServiceInfrastructure;
using MusicServiceInfrastructure.ViewModel;

namespace MusicServiceInfrastructure.Controllers
{
    public class SongsController : Controller
    {
        private readonly ILogger<SongsController> _logger;
        private readonly DbmusicServiceContext _context;
        private readonly UserManager<User> _userManager;

        public SongsController(ILogger<SongsController> logger, DbmusicServiceContext context, UserManager<User> userManager)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
        }

        // GET: Songs
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);

            var model = _context.Songs
                .Select(song => new SongsViewModel
                {
                    Id = song.Id,
                    Title = song.Title,
                    ArtistName = _context.Artists.FirstOrDefault(artist => artist.Id == song.ArtistId).Name,
                    GenreName = _context.Genres.FirstOrDefault(genre => genre.Id == song.GenreId).Name,
                    LyricsText = _context.Lyrics.FirstOrDefault(lyric => lyric.Id == song.LyricsId).Text,
                    AlbumName = _context.Albums.FirstOrDefault(album => album.Id == song.AlbumId).Title,
                    Duration = song.Duration
                })
                .ToList();

            return View(model);
        }

        // GET: Songs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (song == null)
            {
                return NotFound();
            }

            var songViewModel = new SongsViewModel
            {
                Id = song.Id,
                Title = song.Title,
                ArtistName = _context.Artists.FirstOrDefault(artist => artist.Id == song.ArtistId).Name,
                GenreName = _context.Genres.FirstOrDefault(genre => genre.Id == song.GenreId).Name,
                LyricsText = _context.Lyrics.FirstOrDefault(lyric => lyric.Id == song.LyricsId).Text,
                AlbumName = _context.Albums.FirstOrDefault(album => album.Id == song.AlbumId).Title,
                Duration = song.Duration
            };

            return View(songViewModel);
        }

        // GET: Songs/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewData["ArtistId"] = new SelectList(_context.Artists, "Id", "Name");
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name");
            ViewData["AlbumId"] = new SelectList(_context.Albums, "Id", "Title");
            var unusedLyrics = _context.Lyrics.Where(l => !_context.Songs.Any(s => s.LyricsId == l.Id)).ToList();
            ViewData["LyricsId"] = new SelectList(unusedLyrics, "Id", "Text");
            return View();
        }

        // POST: Songs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create([Bind("Title,ArtistId,GenreId,LyricsId,Duration,AlbumId,Id")] Song song)
        {
            if (ModelState.IsValid)
            {
                _context.Add(song);
                await _context.SaveChangesAsync();
                var lyrics = await _context.Lyrics.FindAsync(song.LyricsId);

                if (lyrics != null)
                {
                    lyrics.SongId = song.Id;
                    _context.Update(lyrics);
                }

                SongsArtist sa = new SongsArtist();
                sa.SongId = song.Id;
                sa.ArtistId = song.ArtistId;
                _context.Add(sa);

                SongsGenre sg = new SongsGenre();
                sg.SongId = song.Id;
                sg.GenreId = song.GenreId;
                _context.Add(sg);

                SongsAlbum sal = new SongsAlbum();
                sal.SongId = song.Id;
                sal.AlbumId = song.AlbumId;
                _context.Add(sal);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(song);
        }

        // GET: Songs/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }

            ViewData["ArtistId"] = new SelectList(_context.Artists, "Id", "Name", song.ArtistId);
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", song.GenreId);
            ViewData["AlbumId"] = new SelectList(_context.Albums, "Id", "Title", song.AlbumId);

            var allLyrics = await _context.Lyrics.ToListAsync();

            var associatedLyricsIds = _context.Songs.Where(s => s.LyricsId != null && s.Id != song.Id).Select(s => s.LyricsId).ToList();

            var unusedLyrics = allLyrics.Where(lyric => !associatedLyricsIds.Contains(lyric.Id) || lyric.Id == song.LyricsId).ToList();

            ViewData["LyricsId"] = new SelectList(unusedLyrics, "Id", "Text", song.LyricsId);

            return View(song);
        }



        // POST: Songs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Title,LyricsId,ArtistId,AlbumId,GenreId,Duration,Id")] Song song)
        {
            if (id != song.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(song);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SongExists(song.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(song);
        }


        // GET: Songs/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }

        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var song = await _context.Songs.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }

            var songArtists = await _context.SongsArtists.Where(sa => sa.SongId == id).ToListAsync();
            _context.SongsArtists.RemoveRange(songArtists);

            var songGenres = await _context.SongsGenres.Where(sg => sg.SongId == id).ToListAsync();
            _context.SongsGenres.RemoveRange(songGenres);

            var songAlbums = await _context.SongsAlbums.Where(sal => sal.SongId == id).ToListAsync();
            _context.SongsAlbums.RemoveRange(songAlbums);

            var text = await _context.Lyrics.FirstOrDefaultAsync(t => t.SongId == id);
            if (text != null)
            {
                _context.Lyrics.Remove(text);
            }

            _context.Songs.Remove(song);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SongExists(int id)
        {
            return _context.Songs.Any(e => e.Id == id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Import(IFormFile fileExcel)
        {
            int count = 0;
            if (ModelState.IsValid)
            {
                if (fileExcel != null && Path.GetExtension(fileExcel.FileName).Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
                {
                        using (var stream = new MemoryStream())
                        {
                            await fileExcel.CopyToAsync(stream);
                            stream.Position = 0;

                            using (XLWorkbook workBook = new XLWorkbook(stream))
                            {
                                foreach (IXLWorksheet worksheet in workBook.Worksheets)

MusicServiceInfrastructure/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<MusicServiceDomain.Model.User> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicBox</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_state.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MusicServiceInfrastructure.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Dancing+Script&display=swap">
    <style>
        .btn-custom {
            color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">MusicBox</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Songs" asp-action="Index">Пісні</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && (User.IsInRole("admin") || User.IsInRole("user") || User.IsInRole("system_admin")))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Artists" asp-action="Index">Виконавці</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Genres" asp-action="Index">Жанри</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Lyrics" asp-action="Index">Тексти</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Albums" asp-action="Index">Альбоми</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("system_admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Roles" asp-action="Index">Управління ролями</a>
                            </li>
                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <button type="button" class="btn btn-custom">@User.Identity.Name</button>

                        <form method="post" asp-controller="Account" asp-action="Logout" class="d-flex">
                            <button type="submit" class="btn btn-dark">Вихід</button>
                        </form>
                    }
                    else
                    {
                        <div class="d-flex">
                            <form method="get" asp-controller="Account" asp-action="Login" class="me-2">
                                <button type="submit" class="btn btn-dark">Вхід</button>
                            </form>
                            <form method="get" asp-controller="Account" asp-action="Register">
                                <button type="submit" class="btn btn-outline-dark">Реєстрація</button>
                            </form>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - ЮРЕВИЧ АННА
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>